#!/usr/bin/env python3
"""GitHub client for Warp Bot — replaces the GitHub MCP server for issue I/O.

Importable API:
    triage_issues(since=None)             → list of pending issue dicts
    fetch_issue(owner, repo, number)      → issue dict with comments
    execute_draft(draft)                  → execute GitHub actions from draft dict
    create_issue(owner, repo, title, body) → created issue dict
    post_comment(owner, repo, number, body)

CLI:
    github_client.py triage [--since TIMESTAMP]
    github_client.py fetch-issue OWNER REPO NUMBER
    github_client.py send-draft DRAFT_FILE
    github_client.py create-issue OWNER REPO TITLE BODY
    github_client.py comment OWNER REPO NUMBER BODY
"""

import argparse
import json
import os
import sys

import requests

GITHUB_PAT = os.environ.get("GITHUB_PAT", "")
if not GITHUB_PAT:
    print("Error: set GITHUB_PAT environment variable", file=sys.stderr)
    sys.exit(1)
API = "https://api.github.com"
DEFAULT_OWNER = "warpem"
DEFAULT_REPO = "warp"

SIGNATURE = """— Warp Bot
THIS IS AN AUTOMATED MESSAGE GENERATED BY AN LLM. IT MAY OR MAY NOT SOLVE YOUR PROBLEM. IF YOU'D LIKE TO SPEAK TO A HUMAN, SAY SO IN YOUR MESSAGE."""


def _headers():
    return {
        "Authorization": f"Bearer {GITHUB_PAT}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _get(path, params=None):
    resp = requests.get(f"{API}{path}", headers=_headers(), params=params, timeout=30)
    resp.raise_for_status()
    return resp.json()


def _post(path, body):
    resp = requests.post(f"{API}{path}", headers=_headers(), json=body, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_me():
    return _get("/user")["login"]


# ---------------------------------------------------------------------------
# Functional API
# ---------------------------------------------------------------------------

def triage_issues(since: str | None = None) -> list[dict]:
    """Find unprocessed GitHub issues. Returns list of pending item dicts."""
    me = get_me()

    params = {"state": "open", "per_page": 100}
    if since:
        params["since"] = since

    issues = []
    page = 1
    while True:
        params["page"] = page
        batch = _get(f"/repos/{DEFAULT_OWNER}/{DEFAULT_REPO}/issues", params)
        if not batch:
            break
        issues.extend(batch)
        if len(batch) < 100:
            break
        page += 1

    pending = []
    for issue in issues:
        if issue.get("pull_request"):
            continue

        number = issue["number"]
        comments = _get(f"/repos/{DEFAULT_OWNER}/{DEFAULT_REPO}/issues/{number}/comments")

        if comments:
            if comments[-1]["user"]["login"] == me:
                continue
        elif since and issue["created_at"] < since:
            continue

        pending.append({
            "type": "issue",
            "owner": DEFAULT_OWNER,
            "repo": DEFAULT_REPO,
            "issue_number": number,
        })

    return pending


def fetch_issue(owner: str, repo: str, number: int) -> dict:
    """Fetch issue + comments as a dict."""
    issue = _get(f"/repos/{owner}/{repo}/issues/{number}")
    comments = _get(f"/repos/{owner}/{repo}/issues/{number}/comments",
                     {"per_page": 100})

    return {
        "owner": owner,
        "repo": repo,
        "issue_number": issue["number"],
        "title": issue["title"],
        "state": issue["state"],
        "author": issue["user"]["login"],
        "created_at": issue["created_at"],
        "body": issue["body"] or "",
        "labels": [l["name"] for l in issue.get("labels", [])],
        "comments": [
            {
                "id": c["id"],
                "author": c["user"]["login"],
                "created_at": c["created_at"],
                "body": c["body"] or "",
            }
            for c in comments
        ],
    }


def execute_draft(draft: dict) -> None:
    """Execute GitHub actions from a draft dict."""
    action = draft.get("action", "skip")
    if action == "skip":
        return

    gh_issue = draft.get("github_issue")

    if draft.get("source") != "issue":
        if gh_issue and action == "issue":
            create_issue_from_spec(gh_issue)
        return

    owner = draft.get("owner", DEFAULT_OWNER)
    repo = draft.get("repo", DEFAULT_REPO)
    number = draft.get("issue_number")

    if action == "reply":
        reply_text = draft.get("reply", "")
        if not reply_text:
            print("  Error: no reply text in draft", file=sys.stderr)
            sys.exit(1)
        post_comment(owner, repo, number, reply_text)

    elif action == "escalate":
        body = f"A developer has been notified and will follow up.\n\n{SIGNATURE}"
        post_comment(owner, repo, number, body)

    elif action == "issue":
        if gh_issue:
            create_issue_from_spec(gh_issue)
        reply_text = draft.get("reply", "")
        if reply_text:
            post_comment(owner, repo, number, reply_text)

    else:
        print(f"  Unknown action: {action}", file=sys.stderr)


def create_issue(owner: str, repo: str, title: str, body: str) -> dict:
    """Create a new GitHub issue. Returns the API response."""
    result = _post(f"/repos/{owner}/{repo}/issues", {"title": title, "body": body})
    print(f"  Created issue: {result['html_url']}")
    return result


def create_issue_from_spec(spec: dict) -> dict:
    """Create a GitHub issue from a draft's github_issue spec."""
    repo_full = spec.get("repo", f"{DEFAULT_OWNER}/{DEFAULT_REPO}")
    owner, repo = repo_full.split("/")
    return create_issue(owner, repo, spec["title"], spec["body"])


def post_comment(owner: str, repo: str, number: int, body: str) -> None:
    """Post a comment on a GitHub issue."""
    _post(f"/repos/{owner}/{repo}/issues/{number}/comments", {"body": body})
    print(f"  Commented on {owner}/{repo}#{number}")


# ---------------------------------------------------------------------------
# CLI wrappers
# ---------------------------------------------------------------------------

def cmd_triage(args):
    pending = triage_issues(since=args.since)

    existing = []
    try:
        with open("pending_messages.json") as f:
            existing = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    existing.extend(pending)
    with open("pending_messages.json", "w") as f:
        json.dump(existing, f, indent=2)

    print(f"{len(pending)} unprocessed issue(s)")


def cmd_fetch_issue(args):
    result = fetch_issue(args.owner, args.repo, args.number)
    json.dump(result, sys.stdout, indent=2, ensure_ascii=False)
    print()


def cmd_send_draft(args):
    with open(args.draft_file) as f:
        draft = json.load(f)
    execute_draft(draft)


def cmd_create_issue(args):
    create_issue(args.owner, args.repo, args.title, args.body)


def cmd_comment(args):
    post_comment(args.owner, args.repo, args.number, args.body)


def main():
    parser = argparse.ArgumentParser(description="GitHub client for Warp Bot")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("triage")
    p.add_argument("--since")
    p.set_defaults(func=cmd_triage)

    p = sub.add_parser("fetch-issue")
    p.add_argument("owner")
    p.add_argument("repo")
    p.add_argument("number", type=int)
    p.set_defaults(func=cmd_fetch_issue)

    p = sub.add_parser("send-draft")
    p.add_argument("draft_file")
    p.set_defaults(func=cmd_send_draft)

    p = sub.add_parser("create-issue")
    p.add_argument("owner")
    p.add_argument("repo")
    p.add_argument("title")
    p.add_argument("body")
    p.set_defaults(func=cmd_create_issue)

    p = sub.add_parser("comment")
    p.add_argument("owner")
    p.add_argument("repo")
    p.add_argument("number", type=int)
    p.add_argument("body")
    p.set_defaults(func=cmd_comment)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
